on:
  push:
    branches:
      - 'main'
  delete:
    branches:
      - 'feature**'
jobs:
  build-deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Build and Test
        run: |
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          export SAM_CLI_TELEMETRY=0
          go version
          sam build
          go test ./... -v
      - name: build function
        run: |
          sam validate
          sam build
          sam deploy --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset
